# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20151020_1050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set([]),
        ),
    ]
